version: "3.4"

services:

  db:
    image: postgres:9.4
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: customerdb
    networks:
    - bravi
    deploy:
      placement:
        constraints: [node.role == manager]

  braviapp:
    image: current-version
    ports:
    - 8090:8090
    networks:
    - bravi
    depends_on:
    - db
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=TEST-BRAVI]
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  bravi:

volumes:
  db-data: